name: Deploy to EC2

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Connect to EC2 and Deploy Docker Compose
      run: |
        set -e  # Exit immediately if a command exits with a non-zero status
        echo "Connecting to EC2 instance and deploying application..."
        ssh -o StrictHostKeyChecking=no ec2-user@54.234.235.218 << 'EOF'
          set -e
          echo "Navigating to the application directory..."
          cd /home/ubuntu/my-app || exit
          echo "Pulling latest code from the main branch..."
          git pull origin main
          echo "Stopping and removing existing Docker containers..."
          docker-compose down
          echo "Building and starting Docker containers..."
          docker-compose up -d --build
          echo "Deployment complete."
        EOF
